/****************************************************************************
 ** 
 ** This demo file is part of yFiles WPF 3.4.
 ** Copyright (c) 2000-2021 by yWorks GmbH, Vor dem Kreuzberg 28,
 ** 72070 Tuebingen, Germany. All rights reserved.
 ** 
 ** yFiles demo files exhibit yFiles WPF functionalities. Any redistribution
 ** of demo files in source code or binary form, with or without
 ** modification, is not permitted.
 ** 
 ** Owners of a valid software license for a yFiles WPF version that this
 ** demo is shipped with are allowed to use the demo source code as basis
 ** for their own yFiles WPF powered applications. Use of such programs is
 ** governed by the rights and conditions as set out in the yFiles WPF
 ** license agreement.
 ** 
 ** THIS SOFTWARE IS PROVIDED ''AS IS'' AND ANY EXPRESS OR IMPLIED
 ** WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ** MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN
 ** NO EVENT SHALL yWorks BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 ** SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ** TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 ** PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 ** LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 ** NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 ** SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ** 
 ***************************************************************************/

using System.Windows;
using yWorks.Controls.Input;
using yWorks.Controls;
using yWorks.Geometry;
using yWorks.Graph;
using yWorks.Graph.LabelModels;

namespace Tutorial.CustomStyles
{
  /// <summary>
  /// This demo show how to create and use a relatively simple, non-interactive custom style
  /// for nodes, labels, edges, and ports, as well as a custom arrow.
  /// </summary>
  public partial class SimpleCustomStyleForm
  {

    ////////////////////////////////////////////////////
    //////////////// New in this sample ////////////////
    ////////////////////////////////////////////////////

    /// <summary>
    /// Adds and configures the <see cref="BridgeManager"/>.
    /// </summary>
    private void ConfigureBridges() {
      // create a new BridgeManager
      // The graph item styles are responsible for both 
      // providing obstacles and drawing bridges,
      // the bridge manager collects the obstacles and
      // updates given edge paths to add bridges.
      // see MySimpleEdgeStyle
      var bridgeManager = new BridgeManager();

      //Convenience class that just queries all model item
      GraphObstacleProvider provider = new GraphObstacleProvider();

      //Register an IObstacleProvider, bridgeManager will query all registered obstacle providers
      //to determine if a bridge must be created
      bridgeManager.AddObstacleProvider(provider);
      //Bind the bridge manager to the GraphControl...
      bridgeManager.CanvasControl = graphControl;
    }

    ////////////////////////////////////////////////////
    
    /// <summary>
    /// Sets a custom NodeStyle instance as a template for newly created
    /// nodes in the graph.
    /// </summary>
    protected void InitializeGraph() {
      IGraph graph = graphControl.Graph;

      // Create a new style and use it as default node style
      graph.NodeDefaults.Style = new MySimpleNodeStyle();
      // Create a new style and use it as default edge style
      graph.EdgeDefaults.Style = new MySimpleEdgeStyle();
      
      graph.NodeDefaults.Size = new SizeD(50, 50);

      // Create some graph elements with the above defined styles.
      CreateSampleGraph();
    }

    #region Constructor

    /// <summary>
    /// Automatically generated by Visual Studio.
    /// Wires up the UI components and adds a 
    /// <see cref="GraphControl"/> to the form.
    /// </summary>
    public SimpleCustomStyleForm() {
      InitializeComponent();
    }

    #endregion

    #region Initialization

    /// <summary>
    /// Called upon loading of the form.
    /// This method initializes the graph and the input mode.
    /// </summary>
    /// <seealso cref="InitializeGraph"/>
    protected virtual void OnLoaded(object src, RoutedEventArgs e) {
      // initialize the graph
      InitializeGraph();

      // initialize the input mode
      graphControl.InputMode = CreateEditorMode();

      graphControl.FitGraphBounds();

      //////////////// New in this sample ////////////////
      // Configure the BridgeManager
      ConfigureBridges();
    }

    /// <summary>
    /// Creates the default input mode for the GraphControl,
    /// a <see cref="GraphEditorInputMode"/>.
    /// </summary>
    /// <returns>a new GraphEditorInputMode instance</returns>
    protected virtual IInputMode CreateEditorMode() {
      GraphEditorInputMode mode = new GraphEditorInputMode
                                    {
                                      //We enable label editing
                                      AllowEditLabel = true
                                    };
      return mode;
    }

    #endregion

    #region Graph creation
    /// <summary>
    /// Creates the initial sample graph.
    /// </summary>
    private void CreateSampleGraph() {
      IGraph graph = graphControl.Graph;
      INode node0 = graph.CreateNode(new RectD(-100, -50, 30, 30));
      INode node1 = graph.CreateNode(new RectD(100, -50, 30, 30));
      IEdge edge0 = graph.CreateEdge(node0, node1);
      INode node2 = graph.CreateNode(new RectD(-100, 50, 30, 30));
      INode node3 = graph.CreateNode(new RectD(100, 50, 30, 30));
      IEdge edge2 = graph.CreateEdge(node2, node3);
      INode node4 = graph.CreateNode(new RectD(-50, -100, 30, 30));
      INode node5 = graph.CreateNode(new RectD(-50, 100, 30, 30));
      IEdge edge3 = graph.CreateEdge(node4, node5);
      INode node6 = graph.CreateNode(new RectD(50, -100, 30, 30));
      INode node7 = graph.CreateNode(new RectD(50, 100, 30, 30));
      IEdge edge4 = graph.CreateEdge(node6, node7);
    }

    #endregion

  }
}
